version: '3'
services: 
  xrayr: 
    image: available2099/xraymax:v1
    container_name: boardxrayr1
    volumes:
      - ./config:/etc/XrayR/ # 映射配置文件夹
      - /etc/v2ray-agent/tls/:/etc/v2ray-agent/tls/
    restart: always
    network_mode: host
