version: '3'
services: 
  xrayr: 
    image: hulisang/xrayr:0.8.2.6
    volumes:
      - ./config:/etc/XrayR/ # 映射配置文件夹
      - /etc/v2ray-agent/tls/:/etc/v2ray-agent/tls/
    restart: always
    network_mode: host
