version: '3'
services: 
  xrayr: 
    image: realldz/xrayr:latest
    volumes:
      - ./config:/etc/XrayR/ # 映射配置文件夹
      - /etc/v2ray-agent/tls/:/etc/v2ray-agent/tls/
    restart: always
    network_mode: host
